version: '3'
services:
  application:
    build:
      context: ./application
    image: dash-code-challange-application
    working_dir: ${PWD}/application
    volumes:
      - ./application:${PWD}/application:delegated
      # this is a workaround to prevent host node_modules from accidentally getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /node_modules location.
      - app_node_modules:${PWD}/application/node_modules

volumes:
  app_node_modules:
